"""Harvest drone swarms - presentation + economy."""

from __future__ import annotations

SWARM_BASE_DRONES = 12
SWARM_DRONES_PER_BAY = 18
SWARM_MAX_DRONES = 100
SWARM_DURATION_DAYS = 14.0
SWARM_YIELD_T_PER_DRONE_DAY = 0.85
SWARM_CREDIT_COST_PER_DRONE = 8.0
SWARM_ENERGY_COST_PER_DRONE = 0.04
SWARM_MIN_WINDOW_DAYS = 0.0
SWARM_COOLDOWN_DAYS = 40.0
